### ISSUE TITLE
SequelizeDatabaseError: You have an error in your SQL syntax

### ISSUE THREAD

**Issue by rgaiacs** [CRICDatabase/searchable-image-database-nodejs#16]
When I run

```
sequelize.sync();
```

I get

```
Unhandled rejection SequelizeDatabaseError: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NUMBER, `total_classificacoes` NUMBER, `created_at` DATETIME NOT NULL, `updated_' at line 1
    at Query.formatError (/opt/cric/backend/node_modules/sequelize/lib/dialects/mysql/query.js:244:16)
    at Query.handler [as onResult] (/opt/cric/backend/node_modules/sequelize/lib/dialects/mysql/query.js:51:23)
    at Query.execute (/opt/cric/backend/node_modules/mysql2/lib/commands/command.js:30:14)
    at Connection.handlePacket (/opt/cric/backend/node_modules/mysql2/lib/connection.js:408:32)
    at PacketParser.onPacket (/opt/cric/backend/node_modules/mysql2/lib/connection.js:70:12)
    at PacketParser.executeStart (/opt/cric/backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/opt/cric/backend/node_modules/mysql2/lib/connection.js:77:25)
    at Socket.emit (events.js:316:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at Socket.Readable.push (_stream_readable.js:214:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
```

**Comment by rgaiacs** [comment]
Looks like this is related with https://github.com/CRICDatabase/searchable-image-database-nodejs/issues/10 as bc6c453 might have solve it.
