### ISSUE TITLE
Change password isn't implemented

### ISSUE THREAD

**Issue by rgaiacs** [CRICDatabase/searchable-image-database-nodejs#161]
```
  ● POST /api/v1/usuarios/senha/trocar › unauthorized

    expect(received).toBe(expected) // Object.is equality

    Expected: 401
    Received: 501

      480 |                     .then(
      481 |                         response => {
    > 482 |                             expect(response.statusCode).toBe(HttpStatus.UNAUTHORIZED);
          |                                                         ^
      483 |                         }
      484 |                     );
      485 |             }

      at src/__tests__/user.js:482:57

  ● POST /api/v1/usuarios/senha/trocar › missing new_password1

    expect(received).toBe(expected) // Object.is equality

    Expected: 200
    Received: 501

      503 |                     .then(
      504 |                         response => {
    > 505 |                             expect(response.statusCode).toBe(HttpStatus.OK);
          |                                                         ^
      506 |                         }
      507 |                     );
      508 |             }

      at src/__tests__/user.js:505:57

  ● POST /api/v1/usuarios/senha/trocar › missing new_password2

    expect(received).toBe(expected) // Object.is equality

    Expected: 200
    Received: 501

      526 |                     .then(
      527 |                         response => {
    > 528 |                             expect(response.statusCode).toBe(HttpStatus.OK);
          |                                                         ^
      529 |                         }
      530 |                     );
      531 |             }

      at src/__tests__/user.js:528:57

  ● POST /api/v1/usuarios/senha/trocar › missing old_password

    expect(received).toBe(expected) // Object.is equality

    Expected: 400
    Received: 501

      549 |                     .then(
      550 |                         response => {
    > 551 |                             expect(response.statusCode).toBe(HttpStatus.BAD_REQUEST);
          |                                                         ^
      552 |                         }
      553 |                     );
      554 |             }

      at src/__tests__/user.js:551:57

  ● POST /api/v1/usuarios/senha/trocar › OK

    expect(received).toBe(expected) // Object.is equality

    Expected: 200
    Received: 204

      460 |                                 .then(
      461 |                                     response => {
    > 462 |                                         expect(response.statusCode).toBe(HttpStatus.OK);
          |                                                                     ^
      463 |                                     }
      464 |                                 );
      465 |                         }

      at src/__tests__/user.js:462:69
```

**Comment by rgaiacs** [comment]
@agcbianchi this is a good first task for Marcus.
