### ISSUE TITLE
Can't create image in the database

### ISSUE THREAD

**Issue by rgaiacs** [CRICDatabase/searchable-image-database-nodejs#17]
When I run

```
Imagem.create({
    nome: php_imagem.nome,
    codigo_lamina: php_imagem.lamina,
    excluida: 0,
    classificacao_aprovada: 1,
    dt_aquisicao: date_image,
    fonte_aquisicao: 1,
    caminho_imagem: "imagens/base_interna/",
    altura: 1040,  // Requires later verification
    largura: 1388,  // Requires later verification
    id_usuario: 1,
    id_lesao: 1
});
```

I have

```
Unhandled rejection SequelizeDatabaseError: Field 'id_usuario' doesn't have a default value
    at Query.formatError (/opt/cric/backend/node_modules/sequelize/lib/dialects/mysql/query.js:244:16)
    at Execute.handler [as onResult] (/opt/cric/backend/node_modules/sequelize/lib/dialects/mysql/query.js:51:23)
    at Execute.execute (/opt/cric/backend/node_modules/mysql2/lib/commands/command.js:30:14)
    at Connection.handlePacket (/opt/cric/backend/node_modules/mysql2/lib/connection.js:408:32)
    at PacketParser.onPacket (/opt/cric/backend/node_modules/mysql2/lib/connection.js:70:12)
    at PacketParser.executeStart (/opt/cric/backend/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/opt/cric/backend/node_modules/mysql2/lib/connection.js:77:25)
    at Socket.emit (events.js:316:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at Socket.Readable.push (_stream_readable.js:214:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
```

What is wrong with the code?

**Comment by rgaiacs** [comment]
Using the API.
