### ISSUE TITLE
DELETE /api/v1/lesoes/:id_lesoes(\d+) isn't implemented

### ISSUE THREAD

**Issue by rgaiacs** [CRICDatabase/searchable-image-database-nodejs#177]
```
  ● DELETE /api/v1/lesoes/:id_lesoes(\d+) › anonymous
    expect(received).toBe(expected) // Object.is equality
    Expected: 401
    Received: 501
      762 |                     .then(
      763 |                         response => {
    > 764 |                             expect(response.statusCode).toBe(HttpStatus.UNAUTHORIZED);
          |                                                         ^
      765 |                         }
      766 |                     );
      767 |             }
      at src/__tests__/injury.js:764:57
          at runMicrotasks (<anonymous>)
  ● DELETE /api/v1/lesoes/:id_lesoes(\d+) › charles
    expect(received).toBe(expected) // Object.is equality
    Expected: 403
    Received: 501
      779 |                     .then(
      780 |                         response => {
    > 781 |                             expect(response.statusCode).toBe(HttpStatus.FORBIDDEN);
          |                                                         ^
      782 |                         }
      783 |                     );
      784 |             }
      at src/__tests__/injury.js:781:57
          at runMicrotasks (<anonymous>)
  ● DELETE /api/v1/lesoes/:id_lesoes(\d+) › admin
    expect(received).toBe(expected) // Object.is equality
    Expected: 204
    Received: 501
      796 |                     .then(
      797 |                         response => {
    > 798 |                             expect(response.statusCode).toBe(HttpStatus.NO_CONTENT);
          |                                                         ^
      799 |                         }
      800 |                     );
      801 |             }
      at src/__tests__/injury.js:798:57
          at runMicrotasks (<anonymous>)
```

**Comment by rgaiacs** [comment]
@agcbianchi what should be done with image and cells that are associate with the deleted injury?

**Comment by agcbianchi** [comment]
Keep them in a directory with a date for 1 month. 
So after 1 mont, someone may delete them if they were not used.
