### ISSUE TITLE
Unexpected token e in JSON

### ISSUE THREAD

**Issue by rgaiacs** [CRICDatabase/searchable-image-database-nodejs#36]
http://database.cric.com.br/ is making the following request when attempting user authentication

```
$ cat example.sh 
curl --verbose \
    -H "token_autenticacao: bac8db9147ac80b4ba8a05bb0de7c4fd" \
    -H "Content-Type: application/json" \
    --data '{email: "nupeb@ufop.edu.br", senha: "secret"}' \
    -X GET "http://database.cric.com.br/api/v1/usuarios/"
[raniere@ssi] /tmp
$ bash example.sh
*   Trying 165.227.241.43:80...
* TCP_NODELAY set
* Connected to database.cric.com.br (165.227.241.43) port 80 (#0)
> GET /api/v1/usuarios/ HTTP/1.1
> Host: database.cric.com.br
> User-Agent: curl/7.65.3
> Accept: */*
> token_autenticacao: bac8db9147ac80b4ba8a05bb0de7c4fd
> Content-Type: application/json
> Content-Length: 45
> 
* upload completely sent off: 45 out of 45 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< Server: nginx/1.17.8
< Date: Sat, 04 Apr 2020 23:05:30 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 892
< Connection: keep-alive
< X-Powered-By: Express
< Content-Security-Policy: default-src 'none'
< X-Content-Type-Options: nosniff
< 
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>SyntaxError: Unexpected token e in JSON at position 1<br> &nbsp; &nbsp;at JSON.parse (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at parse (/opt/cric/backend/node_modules/body-parser/lib/types/json.js:89:19)<br> &nbsp; &nbsp;at /opt/cric/backend/node_modules/body-parser/lib/read.js:121:18<br> &nbsp; &nbsp;at invokeCallback (/opt/cric/backend/node_modules/raw-body/index.js:224:16)<br> &nbsp; &nbsp;at done (/opt/cric/backend/node_modules/raw-body/index.js:213:7)<br> &nbsp; &nbsp;at IncomingMessage.onEnd (/opt/cric/backend/node_modules/raw-body/index.js:273:7)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:328:22)<br> &nbsp; &nbsp;at endReadableNT (_stream_readable.js:1201:12)<br> &nbsp; &nbsp;at processTicksAndRejections (internal/process/task_queues.js:84:21)</pre>
</body>
</html>
* Connection #0 to host database.cric.com.br left intact
```

When including double quotes in the JSON keys, it works:

```
$ cat example.sh 
curl --verbose \
    -H "token_autenticacao: bac8db9147ac80b4ba8a05bb0de7c4fd" \
    -H "Content-Type: application/json" \
    --data '{"email": "nupeb@ufop.edu.br", "senha": "secret"}' \
    -X GET "http://database.cric.com.br/api/v1/usuarios/"
[raniere@ssi] /tmp
$ bash example.sh
*   Trying 165.227.241.43:80...
* TCP_NODELAY set
* Connected to database.cric.com.br (165.227.241.43) port 80 (#0)
> GET /api/v1/usuarios/ HTTP/1.1
> Host: database.cric.com.br
> User-Agent: curl/7.65.3
> Accept: */*
> token_autenticacao: bac8db9147ac80b4ba8a05bb0de7c4fd
> Content-Type: application/json
> Content-Length: 49
> 
* upload completely sent off: 49 out of 49 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
< Server: nginx/1.17.8
< Date: Sat, 04 Apr 2020 23:07:44 GMT
< Content-Type: application/json; charset=utf-8
< Content-Length: 53
< Connection: keep-alive
< X-Powered-By: Express
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Headers: *
< Access-Control-Allow-Methods: *
< ETag: W/"35-zBkCcivUJ7NoWc2vxazjAiWt4PA"
< 
* Connection #0 to host database.cric.com.br left intact
{"status_code":401,"mensagem":"Access token invalid"}
```

This doesn't happen when I try locally.

**Comment by bernardofagner** [comment]
O javascript não exige o uso de aspas no nome da propriedade pois o nome é um objeto (email) que tem um valor associado (nuped@ufop...). Este objeto é serializado e transformado para o formato json, neste formado ele possui aspas duplas no nome da propriedade ("email").  Então, qualquer requisição que você quiser simular em formato json, você deve se atentar para inserir aspas duplas tanto no nome da propriedade quanto no valor dela ({"chave":"valor"}).
